
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.0.0
 * Query Engine version: 0c19ccc313cf9911a90d99d2ac2eb0280c76c513
 */
Prisma.prismaVersion = {
  client: "7.0.0",
  engine: "0c19ccc313cf9911a90d99d2ac2eb0280c76c513"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.Backend_event_logsScalarFieldEnum = {
  id: 'id',
  event_name: 'event_name',
  error_level: 'error_level',
  function_name: 'function_name',
  user_id: 'user_id',
  payload: 'payload',
  request_id: 'request_id',
  created_at: 'created_at',
  created_commit_id: 'created_commit_id'
};

exports.Prisma.ConfigScalarFieldEnum = {
  key: 'key',
  value: 'value',
  description: 'description'
};

exports.Prisma.Content_reportsScalarFieldEnum = {
  id: 'id',
  target_type: 'target_type',
  target_id: 'target_id',
  reporter_user_id: 'reporter_user_id',
  reason_code: 'reason_code',
  reason_text: 'reason_text',
  status: 'status',
  resolved_at: 'resolved_at',
  resolution_note: 'resolution_note',
  created_version: 'created_version',
  created_at: 'created_at',
  updated_at: 'updated_at',
  lock_no: 'lock_no'
};

exports.Prisma.Contribution_tasksScalarFieldEnum = {
  id: 'id',
  type: 'type',
  task_key: 'task_key',
  target_type: 'target_type',
  target_id: 'target_id',
  payload: 'payload',
  result: 'result',
  user_id: 'user_id',
  created_at: 'created_at'
};

exports.Prisma.Dish_categoriesScalarFieldEnum = {
  id: 'id',
  label_en: 'label_en',
  labels: 'labels',
  image_url: 'image_url',
  tags: 'tags',
  created_at: 'created_at',
  macro_genre_qid: 'macro_genre_qid',
  synced_at: 'synced_at'
};

exports.Prisma.Dish_category_featuresScalarFieldEnum = {
  dish_category_id: 'dish_category_id',
  feature_type: 'feature_type',
  feature_key: 'feature_key',
  score: 'score',
  synced_at: 'synced_at'
};

exports.Prisma.Dish_category_group_vote_candidate_votesScalarFieldEnum = {
  participant_id: 'participant_id',
  candidate_id: 'candidate_id',
  reaction: 'reaction',
  created_at: 'created_at'
};

exports.Prisma.Dish_category_group_vote_candidatesScalarFieldEnum = {
  id: 'id',
  session_id: 'session_id',
  dish_category_id: 'dish_category_id',
  display_name: 'display_name',
  tagline: 'tagline',
  image_url: 'image_url',
  dish_media_ids: 'dish_media_ids',
  dish_media_search_status: 'dish_media_search_status',
  display_order: 'display_order',
  deleted_at: 'deleted_at',
  created_at: 'created_at'
};

exports.Prisma.Dish_category_group_vote_participantsScalarFieldEnum = {
  id: 'id',
  session_id: 'session_id',
  user_id: 'user_id',
  display_name: 'display_name',
  comment: 'comment',
  created_at: 'created_at'
};

exports.Prisma.Dish_category_group_vote_sessionsScalarFieldEnum = {
  id: 'id',
  host_user_id: 'host_user_id',
  share_token: 'share_token',
  search_context: 'search_context',
  created_at: 'created_at',
  updated_at: 'updated_at',
  idempotency_key: 'idempotency_key'
};

exports.Prisma.Dish_category_localized_textScalarFieldEnum = {
  dish_category_id: 'dish_category_id',
  locale: 'locale',
  topic_title: 'topic_title',
  tagline: 'tagline',
  synced_at: 'synced_at'
};

exports.Prisma.Dish_category_variantsScalarFieldEnum = {
  id: 'id',
  dish_category_id: 'dish_category_id',
  surface_form: 'surface_form',
  source: 'source',
  created_at: 'created_at'
};

exports.Prisma.Dish_mediaScalarFieldEnum = {
  id: 'id',
  dish_id: 'dish_id',
  user_id: 'user_id',
  media_path: 'media_path',
  media_type: 'media_type',
  thumbnail_path: 'thumbnail_path',
  created_at: 'created_at',
  updated_at: 'updated_at',
  lock_no: 'lock_no',
  video_duration_ms: 'video_duration_ms',
  media_processing_status: 'media_processing_status',
  thumbnail_processing_status: 'thumbnail_processing_status',
  render_type: 'render_type',
  deleted_at: 'deleted_at'
};

exports.Prisma.Dish_media_analysis_resultsScalarFieldEnum = {
  dish_media_id: 'dish_media_id',
  impr_total: 'impr_total',
  view_total: 'view_total',
  skip_total: 'skip_total',
  completion_total: 'completion_total',
  watch_ms_total: 'watch_ms_total',
  save_total: 'save_total',
  like_total: 'like_total',
  open_map_total: 'open_map_total',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Dish_media_external_embeddingsScalarFieldEnum = {
  dish_media_id: 'dish_media_id',
  dish_id: 'dish_id',
  provider: 'provider',
  external_content_id: 'external_content_id',
  canonical_url: 'canonical_url',
  embed_status: 'embed_status',
  last_verified_at: 'last_verified_at',
  created_at: 'created_at',
  updated_at: 'updated_at',
  thumbnail_url: 'thumbnail_url'
};

exports.Prisma.Dish_media_impressionsScalarFieldEnum = {
  id: 'id',
  dish_media_id: 'dish_media_id',
  user_id: 'user_id',
  session_id: 'session_id',
  source: 'source',
  created_at: 'created_at'
};

exports.Prisma.Dish_media_likesScalarFieldEnum = {
  id: 'id',
  dish_media_id: 'dish_media_id',
  user_id: 'user_id',
  created_at: 'created_at'
};

exports.Prisma.Dish_media_viewsScalarFieldEnum = {
  id: 'id',
  impression_id: 'impression_id',
  dish_media_id: 'dish_media_id',
  user_id: 'user_id',
  started_at: 'started_at',
  watch_ms: 'watch_ms',
  is_completed: 'is_completed',
  is_skipped: 'is_skipped',
  rewatch_count: 'rewatch_count'
};

exports.Prisma.Dish_reviewsScalarFieldEnum = {
  id: 'id',
  dish_id: 'dish_id',
  comment: 'comment',
  original_language_code: 'original_language_code',
  user_id: 'user_id',
  rating: 'rating',
  price_cents: 'price_cents',
  currency_code: 'currency_code',
  created_dish_media_id: 'created_dish_media_id',
  imported_user_name: 'imported_user_name',
  imported_user_avatar: 'imported_user_avatar',
  created_at: 'created_at',
  updated_at: 'updated_at',
  lock_no: 'lock_no',
  deleted_at: 'deleted_at',
  eaten_at: 'eaten_at'
};

exports.Prisma.DishesScalarFieldEnum = {
  id: 'id',
  restaurant_id: 'restaurant_id',
  category_id: 'category_id',
  name: 'name',
  created_at: 'created_at',
  updated_at: 'updated_at',
  lock_no: 'lock_no',
  data_origin: 'data_origin',
  synced_at: 'synced_at'
};

exports.Prisma.External_api_logsScalarFieldEnum = {
  id: 'id',
  request_id: 'request_id',
  function_name: 'function_name',
  api_name: 'api_name',
  endpoint: 'endpoint',
  method: 'method',
  request_payload: 'request_payload',
  response_payload: 'response_payload',
  status_code: 'status_code',
  error_message: 'error_message',
  response_time_ms: 'response_time_ms',
  user_id: 'user_id',
  created_at: 'created_at',
  created_commit_id: 'created_commit_id'
};

exports.Prisma.Frontend_event_logsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  event_name: 'event_name',
  error_level: 'error_level',
  path_name: 'path_name',
  payload: 'payload',
  created_at: 'created_at',
  created_app_version: 'created_app_version',
  created_commit_id: 'created_commit_id'
};

exports.Prisma.Notification_recipientsScalarFieldEnum = {
  notification_id: 'notification_id',
  recipient_id: 'recipient_id',
  thread_updated_at: 'thread_updated_at',
  created_at: 'created_at'
};

exports.Prisma.NotificationsScalarFieldEnum = {
  id: 'id',
  action_type: 'action_type',
  target_table: 'target_table',
  target_id: 'target_id',
  actor_ids: 'actor_ids',
  idempotency_key: 'idempotency_key',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.PayoutsScalarFieldEnum = {
  id: 'id',
  bid_id: 'bid_id',
  transfer_id: 'transfer_id',
  dish_media_id: 'dish_media_id',
  amount_cents: 'amount_cents',
  currency_code: 'currency_code',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at',
  lock_no: 'lock_no'
};

exports.Prisma.PermissionsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
};

exports.Prisma.Prompt_familiesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  purpose: 'purpose',
  weight: 'weight'
};

exports.Prisma.Prompt_usagesScalarFieldEnum = {
  id: 'id',
  family_id: 'family_id',
  variant_id: 'variant_id',
  target_type: 'target_type',
  target_id: 'target_id',
  generated_text: 'generated_text',
  used_prompt_text: 'used_prompt_text',
  input_data: 'input_data',
  llm_model: 'llm_model',
  temperature: 'temperature',
  generated_user: 'generated_user',
  created_at: 'created_at',
  created_request_id: 'created_request_id',
  metadata: 'metadata'
};

exports.Prisma.Prompt_variantsScalarFieldEnum = {
  id: 'id',
  family_id: 'family_id',
  variant_number: 'variant_number',
  prompt_text: 'prompt_text',
  improvement_note: 'improvement_note',
  created_by: 'created_by',
  metadata: 'metadata'
};

exports.Prisma.ReactionsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  target_type: 'target_type',
  target_id: 'target_id',
  action_type: 'action_type',
  meta: 'meta',
  created_at: 'created_at',
  created_version: 'created_version',
  lock_no: 'lock_no'
};

exports.Prisma.Restaurant_bidsScalarFieldEnum = {
  id: 'id',
  restaurant_id: 'restaurant_id',
  user_id: 'user_id',
  payment_intent_id: 'payment_intent_id',
  amount_cents: 'amount_cents',
  currency_code: 'currency_code',
  start_date: 'start_date',
  end_date: 'end_date',
  status: 'status',
  refund_id: 'refund_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  lock_no: 'lock_no'
};

exports.Prisma.RestaurantsScalarFieldEnum = {
  id: 'id',
  google_place_id: 'google_place_id',
  name: 'name',
  name_language_code: 'name_language_code',
  latitude: 'latitude',
  longitude: 'longitude',
  image_url: 'image_url',
  address_components: 'address_components',
  plus_code: 'plus_code',
  created_at: 'created_at',
  image_path: 'image_path',
  source_seed_id: 'source_seed_id',
  source_names: 'source_names',
  source_row_hash: 'source_row_hash',
  synced_at: 'synced_at'
};

exports.Prisma.Role_permissionsScalarFieldEnum = {
  role_id: 'role_id',
  permission_id: 'permission_id'
};

exports.Prisma.RolesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
};

exports.Prisma.Share_linksScalarFieldEnum = {
  id: 'id',
  token_digest: 'token_digest',
  schema_version: 'schema_version',
  target_type: 'target_type',
  target_id: 'target_id',
  target_params: 'target_params',
  preview_locale: 'preview_locale',
  preview_title: 'preview_title',
  preview_description: 'preview_description',
  preview_image_path: 'preview_image_path',
  created_by: 'created_by',
  status: 'status',
  expires_at: 'expires_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.User_device_tokensScalarFieldEnum = {
  user_id: 'user_id',
  expo_push_token: 'expo_push_token',
  updated_at: 'updated_at'
};

exports.Prisma.User_notification_cursorsScalarFieldEnum = {
  user_id: 'user_id',
  last_read_at: 'last_read_at'
};

exports.Prisma.User_notification_preferencesScalarFieldEnum = {
  user_id: 'user_id',
  category: 'category',
  enabled: 'enabled',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.User_rolesScalarFieldEnum = {
  user_id: 'user_id',
  role_id: 'role_id'
};

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  display_name: 'display_name',
  bio: 'bio',
  last_login_at: 'last_login_at',
  created_at: 'created_at',
  updated_at: 'updated_at',
  lock_no: 'lock_no',
  username: 'username',
  preferred_locale: 'preferred_locale',
  avatar_path: 'avatar_path',
  deleted_at: 'deleted_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.backend_event_logs_error_level = exports.$Enums.backend_event_logs_error_level = {
  verbose: 'verbose',
  debug: 'debug',
  log: 'log',
  warn: 'warn',
  error: 'error'
};

exports.frontend_event_logs_error_level = exports.$Enums.frontend_event_logs_error_level = {
  verbose: 'verbose',
  debug: 'debug',
  log: 'log',
  warn: 'warn',
  error: 'error'
};

exports.payout_status = exports.$Enums.payout_status = {
  pending: 'pending',
  paid: 'paid',
  refunded: 'refunded'
};

exports.prompt_families_purpose = exports.$Enums.prompt_families_purpose = {
  spot_guide_manuscript: 'spot_guide_manuscript'
};

exports.restaurant_bid_status = exports.$Enums.restaurant_bid_status = {
  pending: 'pending',
  paid: 'paid',
  refunded: 'refunded'
};

exports.Prisma.ModelName = {
  backend_event_logs: 'backend_event_logs',
  config: 'config',
  content_reports: 'content_reports',
  contribution_tasks: 'contribution_tasks',
  dish_categories: 'dish_categories',
  dish_category_features: 'dish_category_features',
  dish_category_group_vote_candidate_votes: 'dish_category_group_vote_candidate_votes',
  dish_category_group_vote_candidates: 'dish_category_group_vote_candidates',
  dish_category_group_vote_participants: 'dish_category_group_vote_participants',
  dish_category_group_vote_sessions: 'dish_category_group_vote_sessions',
  dish_category_localized_text: 'dish_category_localized_text',
  dish_category_variants: 'dish_category_variants',
  dish_media: 'dish_media',
  dish_media_analysis_results: 'dish_media_analysis_results',
  dish_media_external_embeddings: 'dish_media_external_embeddings',
  dish_media_impressions: 'dish_media_impressions',
  dish_media_likes: 'dish_media_likes',
  dish_media_views: 'dish_media_views',
  dish_reviews: 'dish_reviews',
  dishes: 'dishes',
  external_api_logs: 'external_api_logs',
  frontend_event_logs: 'frontend_event_logs',
  notification_recipients: 'notification_recipients',
  notifications: 'notifications',
  payouts: 'payouts',
  permissions: 'permissions',
  prompt_families: 'prompt_families',
  prompt_usages: 'prompt_usages',
  prompt_variants: 'prompt_variants',
  reactions: 'reactions',
  restaurant_bids: 'restaurant_bids',
  restaurants: 'restaurants',
  role_permissions: 'role_permissions',
  roles: 'roles',
  share_links: 'share_links',
  user_device_tokens: 'user_device_tokens',
  user_notification_cursors: 'user_notification_cursors',
  user_notification_preferences: 'user_notification_preferences',
  user_roles: 'user_roles',
  users: 'users'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
