-- 容量最適化チケット: #760
-- 内容:
-- dish_reviews に定義されていた全文検索用 GIN インデックス
--   `idx_dish_reviews_fulltext` を削除する
--
-- 背景:
--   - DBサイズ逼迫（約472MB）の調査により、
--     当該インデックス（public: 約49MB / dev: 約5.4MB）が
--     大きな容量を占有していることが判明
--   - pg_stat_user_indexes にて idx_scan = 0 を確認
--   - アプリケーションコード上で
--       @@ / to_tsquery / plainto_tsquery / websearch_to_tsquery
--     等の全文検索演算子の利用は未検出
--   - EXPLAIN では使用可能だが、実運用経路では未利用の可能性が高い
--
-- 判断:
--   - 現時点で全文検索機能は実装されていないと判断
--   - 容量削減を優先し、インデックスを削除する
--   - 将来全文検索を実装する場合は再作成可能
--
-- 影響範囲:
--   - comment_tsv 列は削除しない（将来復活可能性を考慮）
--   - 全文検索クエリを新規実装する場合は index 再作成が必要
--   - 既存アプリケーション挙動への影響なし（現状未利用のため）
--
-- 期待効果:
--   - 約54MB のストレージ削減（public + dev）

DROP INDEX IF EXISTS idx_dish_reviews_fulltext;