
-- ============================================
-- Prisma用 本番書き込みロール
-- ============================================
CREATE USER prisma_prod_rw WITH PASSWORD '${PRISMA_PROD_RW_PASSWORD}' BYPASSRLS CREATEDB;
GRANT prisma_prod_rw TO postgres;

GRANT USAGE ON SCHEMA public TO prisma_prod_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO prisma_prod_rw;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO prisma_prod_rw;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO prisma_prod_rw;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO prisma_prod_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO prisma_prod_rw;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO prisma_prod_rw;

-- ==============================================
-- USER: prisma_dev
-- ==============================================

CREATE USER prisma_dev WITH PASSWORD '${PRISMA_PROD_RW_PASSWORD}' BYPASSRLS CREATEDB;

GRANT prisma_dev TO postgres;

-- SCHEMA: public（read-only）
GRANT USAGE ON SCHEMA public TO prisma_dev;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO prisma_dev;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO prisma_dev;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO prisma_dev;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT SELECT ON TABLES TO prisma_dev;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO prisma_dev;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO prisma_dev;

-- SCHEMA: dev（full access）
GRANT USAGE ON SCHEMA dev TO prisma_dev;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dev TO prisma_dev;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA dev TO prisma_dev;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA dev TO prisma_dev;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA dev
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO prisma_dev;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA dev
  GRANT EXECUTE ON FUNCTIONS TO prisma_dev;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA dev
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO prisma_dev;

-- SCHEMA: test（full access）
GRANT USAGE ON SCHEMA test TO prisma_dev;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA test TO prisma_dev;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA test TO prisma_dev;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA test TO prisma_dev;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO prisma_dev;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test
  GRANT EXECUTE ON FUNCTIONS TO prisma_dev;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO prisma_dev;






