import { MD3LightTheme } from "react-native-paper";

export const defaultFonts: typeof MD3LightTheme.fonts = {
	displayLarge: {
		fontFamily: "PlusJakarta-Bold, NotoSans",
		fontWeight: "700",
		fontSize: 57,
		lineHeight: 64,
		letterSpacing: -0.25,
	},
	displayMedium: {
		fontFamily: "PlusJakarta-Bold, NotoSans",
		fontWeight: "700",
		fontSize: 45,
		lineHeight: 52,
		letterSpacing: 0,
	},
	displaySmall: {
		fontFamily: "PlusJakarta-Bold, NotoSans",
		fontWeight: "700",
		fontSize: 36,
		lineHeight: 44,
		letterSpacing: 0,
	},
	headlineLarge: {
		fontFamily: "PlusJakarta-Bold, NotoSans",
		fontWeight: "700",
		fontSize: 32,
		lineHeight: 40,
		letterSpacing: 0,
	},
	headlineMedium: {
		fontFamily: "PlusJakarta-Bold, NotoSans",
		fontWeight: "700",
		fontSize: 28,
		lineHeight: 36,
		letterSpacing: 0,
	},
	headlineSmall: {
		fontFamily: "PlusJakarta-Bold, NotoSans",
		fontWeight: "700",
		fontSize: 24,
		lineHeight: 32,
		letterSpacing: 0,
	},
	titleLarge: {
		fontFamily: "PlusJakarta-Bold, NotoSans",
		fontWeight: "700",
		fontSize: 22,
		lineHeight: 28,
		letterSpacing: 0,
	},
	titleMedium: {
		fontFamily: "PlusJakarta-Bold, NotoSans",
		fontWeight: "600",
		fontSize: 16,
		lineHeight: 24,
		letterSpacing: 0.15,
	},
	titleSmall: {
		fontFamily: "PlusJakarta-Bold, NotoSans",
		fontWeight: "600",
		fontSize: 14,
		lineHeight: 20,
		letterSpacing: 0.1,
	},
	labelLarge: {
		fontFamily: "Inter-Regular, NotoSans",
		fontWeight: "400",
		fontSize: 14,
		lineHeight: 20,
		letterSpacing: 0.1,
	},
	labelMedium: {
		fontFamily: "Inter-Regular, NotoSans",
		fontWeight: "400",
		fontSize: 12,
		lineHeight: 16,
		letterSpacing: 0.5,
	},
	labelSmall: {
		fontFamily: "Inter-Regular, NotoSans",
		fontWeight: "400",
		fontSize: 11,
		lineHeight: 16,
		letterSpacing: 0.5,
	},
	bodyLarge: {
		fontFamily: "Inter-Regular, NotoSans",
		fontWeight: "400",
		fontSize: 16,
		lineHeight: 24,
		letterSpacing: 0.5,
	},
	bodyMedium: {
		fontFamily: "Inter-Regular, NotoSans",
		fontWeight: "400",
		fontSize: 14,
		lineHeight: 20,
		letterSpacing: 0.25,
	},
	bodySmall: {
		fontFamily: "Inter-Regular, NotoSans",
		fontWeight: "400",
		fontSize: 12,
		lineHeight: 16,
		letterSpacing: 0.4,
	},
	default: {
		fontFamily: "Inter-Regular, NotoSans",
		fontWeight: "400",
		letterSpacing: 0.25,
	},
};
